services:
  pedidos-service:
    image: pedidos-service
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile.dev
    ports:
      - "3331:3000"
    volumes:
      - ./pedidos-service:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - kafka
    networks:
      - default
  
  estoque-service:
    image: estoque-service
    build:
      context: ./estoque-service
      dockerfile: Dockerfile.dev
    ports:
      - "3332:3000"
    volumes:
      - ./estoque-service:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - default

  pagamento-service:
    image: pagamento-service
    build:
      context: ./pagamento-service
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3000"
    volumes:
      - ./pagamento-service:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - default

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
        - default

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - zookeeper
    networks:
      - default

networks:
  default:
    driver: bridge